name: post-devto

on:
  push:
    branches:
      - main
    paths:
      - 'devto/**'

jobs:
  post:
    name: Post
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devto
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Install dev-to-git
        run: yarn add dev-to-git

      - name: Post to dev.to
        run: yarn run dev-to-git
        env:
          DEV_TO_GIT_TOKEN: ${{ secrets.DEV_TO_API_KEY }}